pipeline {
    agent any

    environment {
        PATH = "/usr/bin:/usr/local/bin:${env.PATH}"
        // These tell Jenkins exactly where your Minikube files are
        MINIKUBE_HOME = "/home/user"
        KUBECONFIG = "/home/user/.kube/config"
    }

    stages {
        stage('Install') {
            steps {
                dir('node-k8s-app-selinium') {
                    sh 'npm install'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('node-k8s-app-selinium') {
                    sh 'npm test || true'
                }
            }
        }

        stage('Build & Push') {
            steps {
                dir('node-k8s-app-selinium') {
                    sh 'docker build -t kalyani46/my-k8s-app:latest .'
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', 
                                     passwordVariable: 'DOCKER_PASSWORD', 
                                     usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin'
                        sh 'docker push kalyani46/my-k8s-app:latest'
                    }
                }
            }
        }

        stage('Deploy to K8s') {
            steps {
                dir('node-k8s-app-selinium') {
                    // We don't need 'minikube start' here anymore since it's already running
                    sh '''
                    minikube kubectl -- apply -f k8s/deployment.yaml
                    minikube kubectl -- apply -f k8s/service.yaml
                    minikube kubectl -- rollout restart deployment my-k8s-app
                    '''
                }
            }
        }
    }
}
