apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
    spec:
      containers:
      - name: my-k8s-app
        # Updated to match your Docker Hub username from the Jenkins logs
        image: kalyani46/my-k8s-app:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
